{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.paladium.gradle",
    "module": "PalaGradle",
    "version": "1.0.0-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PalaGradle-1.0.0-DEV.jar",
          "url": "PalaGradle-1.0.0-DEV.jar",
          "size": 64144,
          "sha512": "00e2a094fcf7aba10b3e625659f30d1926aec944d2582a301f8ab0889b498d4337e699da1147d63aa2c76c91a7c44891d2701a4be3979b52693116738d010fd1",
          "sha256": "7b2a628d8ba0465747a61f5ab6e2ede81874298ac3025b25bf5ff866bf01321a",
          "sha1": "940bac93fa64d8f826c65fe7648e4cb9636541a9",
          "md5": "4f605269fda3dfbe58056f4163aaa9e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "PalaGradle-1.0.0-DEV.jar",
          "url": "PalaGradle-1.0.0-DEV.jar",
          "size": 64144,
          "sha512": "00e2a094fcf7aba10b3e625659f30d1926aec944d2582a301f8ab0889b498d4337e699da1147d63aa2c76c91a7c44891d2701a4be3979b52693116738d010fd1",
          "sha256": "7b2a628d8ba0465747a61f5ab6e2ede81874298ac3025b25bf5ff866bf01321a",
          "sha1": "940bac93fa64d8f826c65fe7648e4cb9636541a9",
          "md5": "4f605269fda3dfbe58056f4163aaa9e4"
        }
      ]
    }
  ]
}
