{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.paladium.gradle",
    "module": "PalaGradle",
    "version": "1.0.0-DEV",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "PalaGradle-1.0.0-DEV.jar",
          "url": "PalaGradle-1.0.0-DEV.jar",
          "size": 64207,
          "sha512": "28028cb7a76d3c98956598d8066cbeb2b37cbf365d7f476069ed6415fcd2fec52e420b9ebbcec06b0dc0e9d814ac77c2a0768d73a5a4b928db27643f33d921f2",
          "sha256": "69a829bcabcadaf68bef4897f552cc0d2a8aa1e2732a6144b848c305c9489cf1",
          "sha1": "fdfd00c2a6dfb3368ecbebd93afed591ccc309f0",
          "md5": "996420bbd4f81f16b148f6dd6ab7f682"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "PalaGradle-1.0.0-DEV.jar",
          "url": "PalaGradle-1.0.0-DEV.jar",
          "size": 64207,
          "sha512": "28028cb7a76d3c98956598d8066cbeb2b37cbf365d7f476069ed6415fcd2fec52e420b9ebbcec06b0dc0e9d814ac77c2a0768d73a5a4b928db27643f33d921f2",
          "sha256": "69a829bcabcadaf68bef4897f552cc0d2a8aa1e2732a6144b848c305c9489cf1",
          "sha1": "fdfd00c2a6dfb3368ecbebd93afed591ccc309f0",
          "md5": "996420bbd4f81f16b148f6dd6ab7f682"
        }
      ]
    }
  ]
}
